spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tracker_registration_dev?user=root&useSSL=false&useTimezone=true&serverTimezone=UTC&useLegacyDatetimeCode=false
server:
  port: 8083

application:
  oauth-enabled: true